
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EtudiantWSService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8582/EtudiantService?wsdl")
public class EtudiantWSService
    extends Service
{

    private final static URL ETUDIANTWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ETUDIANTWSSERVICE_EXCEPTION;
    private final static QName ETUDIANTWSSERVICE_QNAME = new QName("http://service/", "EtudiantWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8582/EtudiantService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ETUDIANTWSSERVICE_WSDL_LOCATION = url;
        ETUDIANTWSSERVICE_EXCEPTION = e;
    }

    public EtudiantWSService() {
        super(__getWsdlLocation(), ETUDIANTWSSERVICE_QNAME);
    }

    public EtudiantWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ETUDIANTWSSERVICE_QNAME, features);
    }

    public EtudiantWSService(URL wsdlLocation) {
        super(wsdlLocation, ETUDIANTWSSERVICE_QNAME);
    }

    public EtudiantWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ETUDIANTWSSERVICE_QNAME, features);
    }

    public EtudiantWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EtudiantWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EtudiantService
     */
    @WebEndpoint(name = "EtudiantServicePort")
    public EtudiantService getEtudiantServicePort() {
        return super.getPort(new QName("http://service/", "EtudiantServicePort"), EtudiantService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EtudiantService
     */
    @WebEndpoint(name = "EtudiantServicePort")
    public EtudiantService getEtudiantServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "EtudiantServicePort"), EtudiantService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ETUDIANTWSSERVICE_EXCEPTION!= null) {
            throw ETUDIANTWSSERVICE_EXCEPTION;
        }
        return ETUDIANTWSSERVICE_WSDL_LOCATION;
    }

}
