
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EtudiantService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EtudiantService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "AjouterEtudiant")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AjouterEtudiant", targetNamespace = "http://service/", className = "service.AjouterEtudiant")
    @ResponseWrapper(localName = "AjouterEtudiantResponse", targetNamespace = "http://service/", className = "service.AjouterEtudiantResponse")
    @Action(input = "http://service/EtudiantService/AjouterEtudiantRequest", output = "http://service/EtudiantService/AjouterEtudiantResponse")
    public int ajouterEtudiant(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "ModifierEtudiant")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ModifierEtudiant", targetNamespace = "http://service/", className = "service.ModifierEtudiant")
    @ResponseWrapper(localName = "ModifierEtudiantResponse", targetNamespace = "http://service/", className = "service.ModifierEtudiantResponse")
    @Action(input = "http://service/EtudiantService/ModifierEtudiantRequest", output = "http://service/EtudiantService/ModifierEtudiantResponse")
    public int modifierEtudiant(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(operationName = "SupprimerEtudiant")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SupprimerEtudiant", targetNamespace = "http://service/", className = "service.SupprimerEtudiant")
    @ResponseWrapper(localName = "SupprimerEtudiantResponse", targetNamespace = "http://service/", className = "service.SupprimerEtudiantResponse")
    @Action(input = "http://service/EtudiantService/SupprimerEtudiantRequest", output = "http://service/EtudiantService/SupprimerEtudiantResponse")
    public int supprimerEtudiant(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<service.Etudiant>
     */
    @WebMethod(operationName = "GetEudiant")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetEudiant", targetNamespace = "http://service/", className = "service.GetEudiant")
    @ResponseWrapper(localName = "GetEudiantResponse", targetNamespace = "http://service/", className = "service.GetEudiantResponse")
    @Action(input = "http://service/EtudiantService/GetEudiantRequest", output = "http://service/EtudiantService/GetEudiantResponse")
    public List<Etudiant> getEudiant();

}
